### ISSUE TITLE
faster_rcnn_boxes folder not found.

### ISSUE THREAD

**Issue by thanhbouet** [birlrobotics/vs-gats#7]
Hi. I always get error when process data with hico_process.sh. I don't know why but i can't find any "faster_rcnn_boxes" in project. 
Am I missing something to generate that file? Thank u, Hope u still check this.

Traceback:

`Boxes will be read from: D:\python\vs-gats\datasets\processed\hico\faster_rcnn_boxes
Boxes will be written to: D:\python\vs-gats\datasets\processed\hico
Loading anno_list.json ...
Creating selected_coco_cls_dets.hdf5 file ...
Selecting boxes ...
  0%|          | 0/47776 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python\vs-gats\hico_select_confident_boxes.py", line 203, in <module>
    select(data_const)
  File "D:\python\vs-gats\hico_select_confident_boxes.py", line 181, in select
    boxes = np.load(boxes_npy)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gaster Ruu\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python\\vs-gats\\datasets\\processed\\hico\\faster_rcnn_boxes\\HICO_train2015_00000001_boxes.npy'
Loading anno_list.json ...
Evaluating box proposals ...
 80%|#######9  | 38118/47776 [00:00<00:00, 3034380.61it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python\vs-gats\evaluate_instance_detection.py", line 393, in <module>
    evaluate_boxes(data_const)
  File "D:\python\vs-gats\evaluate_instance_detection.py", line 229, in evaluate_boxes
    boxes_scores_rpn_ids = select_boxes[global_id]['boxes_scores_rpn_ids'][()]
                           ~~~~~~~~~~~~^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\Gaster Ruu\AppData\Local\Programs\Python\Python311\Lib\site-packages\h5py\_hl\group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'HICO_test2015_00000001' doesn't exist)"

**Comment by thanhbouet** [comment]
oh i really found the reason
